### ISSUE TITLE
highcharts.src.d.ts cannot be found in tsconfig typeRoots

### ISSUE THREAD

**Issue by antglenn** [sophiebremer/highcharts-declarations-alpha#12]
Hi,

Firstly, thank you for publishing the typings for highcharts 6, however, I have tried to add this to our project and have found that the file cannot be found.

I have added the following to our `tsconfig.json` file:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "noImplicitAny": false,
    "sourceMap": true
  },
  "compileOnSave": true,
  "typeAcquisition": {
    "enable": true
  },
  "typeRoots": [
    "node_modules/@types",
    "node_modules/highcharts"
  ]
}
```

However, the `typeRoots` section of a `tsconfig` file is expecting the path to resolve to `node_modules/highcharts/index.d.ts` however the file is called `highcharts.src.d.ts`. 

As such the file cannot be found and the typings are then unsupported.

This can either be resolved by adding a `types` field to the `package.json` file or by renaming `highcharts.src.d.ts` to `index.d.ts`

Documentation on the `tsconfig.json` can be found here for more detail: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by sophiebremer** [comment]
Hi!

Thank you for your detailed feedback. It is not necessary to define typeRoots to use @types and highcharts modules. Nevertheless I have changed the package file so that you can now use it as a type root as well. Just reinstall the repository.

**Comment by antglenn** [comment]
Hi!

Thank you for updating this so quickly, this has resolved the issue for us. We've a bigger task now of going through and aligning the typings with the published declarations, however that shouldn't be too onerous. 

Thanks again, appreciated.

**Comment by sophiebremer** [comment]
No problem, I am glad I could help that easily.

Please note, that this is an alpha version. The beta package will be released probably next week.
