### ISSUE TITLE
Parameterless call to .highcharts() method missing from Type Definitions

### ISSUE THREAD

**Issue by antglenn** [sophiebremer/highcharts-declarations-alpha#14]
Hi,

We've now put the typings from this into our solution in order to upgrade to version 6 of highcharts, however when going through the typings and code compilation we found that there is no definition for accessing the highcharts object using the following code:

`$('#highcharts-container').highcharts();`

Which if you run in a browser console is valid, and returns the highcharts object bound to the container.

In the interim we have been able to get around this by passing `null` to the highcharts call as follows:

`$('#highcharts-container').highcharts(null);`

This doesn't appear to have any negative affects, however, was not required previously.

Many thanks,

**Comment by sophiebremer** [comment]
The bugfix is part of the pull request https://github.com/highcharts/highcharts/pull/9114 . It will be published with the next beta version of https://github.com/highcharts/highcharts-declarations-beta .
